name: chatiafacilito
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  lottie: ^3.1.2
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  dash_chat_2: ^0.0.21
  flutter_gemini: ^2.0.4
  image_picker: ^1.1.2
  flutter_markdown: ^0.7.3
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
