// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArRRP3uUGw86wxksvrpHZwuGkCe6IG24c',
    appId: '1:125591103691:web:465537c671ec610da8134e',
    messagingSenderId: '125591103691',
    projectId: 'chatfacilito-bdbbe',
    authDomain: 'chatfacilito-bdbbe.firebaseapp.com',
    storageBucket: 'chatfacilito-bdbbe.appspot.com',
    measurementId: 'G-4PVJBCYN1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP9yNKDA1rj5hr9TfhOhVYozT-aMUmZXo',
    appId: '1:125591103691:android:ec8c9e9d88d8c01ba8134e',
    messagingSenderId: '125591103691',
    projectId: 'chatfacilito-bdbbe',
    storageBucket: 'chatfacilito-bdbbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvihru4XL29U4tpu92p7yFnEEmuLN-tok',
    appId: '1:125591103691:ios:a896ced1d53e442ca8134e',
    messagingSenderId: '125591103691',
    projectId: 'chatfacilito-bdbbe',
    storageBucket: 'chatfacilito-bdbbe.appspot.com',
    iosBundleId: 'com.example.chatfacilito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvihru4XL29U4tpu92p7yFnEEmuLN-tok',
    appId: '1:125591103691:ios:a896ced1d53e442ca8134e',
    messagingSenderId: '125591103691',
    projectId: 'chatfacilito-bdbbe',
    storageBucket: 'chatfacilito-bdbbe.appspot.com',
    iosBundleId: 'com.example.chatfacilito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArRRP3uUGw86wxksvrpHZwuGkCe6IG24c',
    appId: '1:125591103691:web:178eb2106ccb7cbfa8134e',
    messagingSenderId: '125591103691',
    projectId: 'chatfacilito-bdbbe',
    authDomain: 'chatfacilito-bdbbe.firebaseapp.com',
    storageBucket: 'chatfacilito-bdbbe.appspot.com',
    measurementId: 'G-S65MQYD502',
  );
}
