// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQZyY8siH6-aNVyE_bD5sLWzVdLbXNZ9M',
    appId: '1:445215285041:web:6377d70c65d904cb5d9a10',
    messagingSenderId: '445215285041',
    projectId: 'chatiafacilito',
    authDomain: 'chatiafacilito.firebaseapp.com',
    storageBucket: 'chatiafacilito.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0J2QOH5dAM4Pk_ntdrAb4dtwTNLavDbM',
    appId: '1:445215285041:android:f6b50e19c44841185d9a10',
    messagingSenderId: '445215285041',
    projectId: 'chatiafacilito',
    storageBucket: 'chatiafacilito.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBXeXesXXwWZnQ3JHNB9QvEfMYtIdnnRQ',
    appId: '1:445215285041:ios:d2d8d9c43f6dc71e5d9a10',
    messagingSenderId: '445215285041',
    projectId: 'chatiafacilito',
    storageBucket: 'chatiafacilito.appspot.com',
    iosBundleId: 'com.example.chatiafacilito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBXeXesXXwWZnQ3JHNB9QvEfMYtIdnnRQ',
    appId: '1:445215285041:ios:d2d8d9c43f6dc71e5d9a10',
    messagingSenderId: '445215285041',
    projectId: 'chatiafacilito',
    storageBucket: 'chatiafacilito.appspot.com',
    iosBundleId: 'com.example.chatiafacilito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQZyY8siH6-aNVyE_bD5sLWzVdLbXNZ9M',
    appId: '1:445215285041:web:ff64da509f3450b85d9a10',
    messagingSenderId: '445215285041',
    projectId: 'chatiafacilito',
    authDomain: 'chatiafacilito.firebaseapp.com',
    storageBucket: 'chatiafacilito.appspot.com',
  );
}
